# TravisCI configuration for hybridauth/hybridauth

language: "php"
os:
  - "linux"
dist: "bionic"

php:
  - "7.4"
  - "7.3"
  - "7.2"
  - "8.0"

jobs:
  include:
    - name: "PHP 5.6"
      dist: "xenial"
      php: "5.6"
    # "php": ">=5.4.0"
    - name: "PHP 5.4"
      dist: "trusty"
      php: "5.4"

cache:
  directories:
    - "${HOME}/.composer/cache"

before_script:
  - "composer validate --strict"

install:
  - "composer install --prefer-dist"
  - "composer global require squizlabs/php_codesniffer"

script:
  - "vendor/bin/phpunit --verbose"
  - "composer global exec -- phpcs -p -s --extensions=php --standard=PSR2 --ignore='./src/Thirdparty/*' ./src"

notifications:
  email: false
